### ISSUE TITLE
Please back filman.cc

### ISSUE THREAD

**Issue by gzenio22** [recloudstream/cloudstream-extensions-multilingual#40]
Przywróććie wtyczke do strony filman.cc

**Comment by Jacob1Tm** [comment]
Aktualnie chyba jest to średnio możliwe, gdyż filman teraz praktycznie do wszystkiego wymaga się zalogować, ale nie wiem ja nie jestem developerem :))

**Comment by C10udburst** [comment]
właściciel filmana był zły że mu premium za darmo oglądali

**Comment by gzenio22** [comment]
To nie dawajcie premium tylko zwykłego filmana

**Comment by Jacob1Tm** [comment]
Teraz widzę, że już chyba zdjęli to wymaganie, bo normalnie wyszukuje bez logowania @C10udburst patrzyłeś czy teraz działa?
~~Bo nie wiem, czy można jakoś ręcznie włączyć filmana~~

**Comment by xKubsoneQ** [comment]
@Jacob1Tm to tak nie działa, filman od jakiegoś czasu jest tak zepsuty, że niektóre filmy/seriale pokazuje Ci normalnie, a po wejściu na zdecydowaną większość materiałów przenosi na /logowanie

**Comment by Jacob1Tm** [comment]
No dobra, aczkolwiek pozwala to i tak na oglądanie sporej części bez logowania, bo głównie te popularniejsze mają to wymaganie

**Comment by xKubsoneQ** [comment]
> No dobra, aczkolwiek pozwala to i tak na oglądanie sporej części bez logowania, bo głównie te popularniejsze mają to wymaganie a inne strony, które są w CS3 no nie mają tak dużo kontentu.

generalnie filman jest chyba największą polską stroną pod względem ilości kontentu

**Comment by gzenio22** [comment]
Filman i vizjer ale ostatnio CS3 nie ogarnia playerów na PL stronach i i tak żadna pozycja sie nie odtwarza mimo że na danej stronie jest np hosting Voe który był obsługiwany przez wtyczke

**Comment by xKubsoneQ** [comment]
pr #49

**Comment by Jacob1Tm** [comment]
kurwa znowu zablokowali wyszukiwanie za logowaniem :
